name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get Libs
      run:  sudo apt-get install gcc libglfw3 libglfw3-dev libglew-dev ffmpeg

    - name: Install dependencies
      run: cd src && make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
